---
version: '3.7'

#volumes:
    #prometheus_data: {}
    #grafana_data: {}

services:

########################################################################################
# Prometheus
# https://quay.io/repository/prometheus/prometheus?tab=info
# https://hub.docker.com/r/prom/prometheus/
# https://prometheus.io/docs/introduction/https://grafana.com/docs/installation/docker/overview/
########################################################################################

  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
        - ./prometheus:/etc/prometheus # Prometheus settings
        - ${VOLUME_DIR}/prometheus:/prometheus # Data directory
        #- prometheus_data:/prometheus # Data directory
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #network_mode: host
    networks:
      - backend
    ports:
      - 9090:9090
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.${FQDN}"
      - "traefik.port=9090"
      - "traefik.docker.network=backend"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

########################################################################################
# Grafana
# https://hub.docker.com/r/grafana/grafana/
# https://grafana.com/docs/installation/docker/
########################################################################################

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: 472 # http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning # Grafana settings and dashboards
      - ${VOLUME_DIR}/grafana:/var/lib/grafana # Data directory
      #- grafana_data:/var/lib/grafana # Data directory
    networks:
      - backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.${FQDN}"
      - "traefik.port=3000"
      - "traefik.docker.network=backend"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

########################################################################################
# Node Exporter
# https://hub.docker.com/r/prom/node-exporter/
# https://github.com/prometheus/node_exporter
# https://prometheus.io/docs/guides/node-exporter/
########################################################################################

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - backend
    restart: always

networks:
  backend:
    external:
      name: backend
      #run: docker network create --name=backend
