# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  # Here it's Prometheus itself.
  - job_name: prometheus
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  # Container monitoring
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  # Nodes
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100'] # Raspberry Pi 4
    - target_label: ['Raspberry Pi 4']

    - targets: ['192.168.1.20:9100']  # Raspberry Pi 3
    - target_label: ['Raspberry Pi 3']
    
    - targets: ['192.168.1.124:9100'] # Lenovo X1 Extreme
    - target_label: ['Lenovo X1 Extreme']