---
- name: Configure Grafana
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Import "Node Exporter Full" dashboard
      community.grafana.grafana_dashboard:
        grafana_url: https://grafana
        grafana_user: "admin"
        grafana_password: "{{ GRAFANA_PASSWORD }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        folder: custom
        dashboard_id: 1860
        dashboard_revision: 1